dawnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('finsys.urls', 'finsys'), namespace='finsys')),
    path('authentication/', include(('users.urls', 'users'), namespace='users')),
]

finsys/company/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("404/", views.CompanyNotFound.as_view(), name="company-404"),
    path("create/", views.CompanyCreateView.as_view(), name="company-create"),
    path("switch/", views.SwitchCompanyView.as_view(), name="company-switch"),
    path("detail/<name>/", views.CompanyDetailView.as_view(), name="company-detail"),
    path("update/<pk>/", views.CompanyUpdateView.as_view(), name="company-update"),
    path("delete/<pk>/", views.CompanyDeleteView.as_view(), name="company-delete"),
    path("member/add/<pk>/", views.MemberCreateView.as_view(), name="company-member-add"),
    path("member/role/change/<pk>/", views.MemberRoleChangeView.as_view(), name="company-role-change"),
    path("member/remove/<pk>/", views.MemberRoleChangeView.as_view(), name="company-member-remove"),


    path("switch/year/", views.YearSwitchView.as_view(), name="company-year-switch"),
]

finsys/urls.py
from django.urls import path, include

from finsys import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),

    path("ledger/", views.AccountListView.as_view(), name="ledger"),
    path("ledger/create/", views.AccountCreateView.as_view(), name="ledger-create"),
    path("ledger/update/<int:pk>/", views.AccountUpdateView.as_view(), name="ledger-update"),
    path("ledger/delete/<int:pk>/", views.AccountDeleteView.as_view(), name="ledger-delete"),
    path("ledger/<int:pk>/", views.AccountDetailView.as_view(), name="ledger-details"),

    path("entries/create/<int:pk>/", views.AccountHistoryCreateView.as_view(), name="entries-create"),
    path("entries/update/<int:pk>/", views.AccountHistoryUpdateView.as_view(), name="entries-update"),
    path("entries/delete/<int:pk>/<int:acc_pk>", views.AccountHistoryDeleteView.as_view(), name="entries-delete"),
    path("entries/history/<int:pk>/", views.AccountHistoryView.as_view(), name="entries-history"),

    path("banks/", views.BankView.as_view(), name="wallet"),
    path("banks/<int:pk>/", views.BankDetailView.as_view(), name="bank-details"),
    path("banks/create/", views.BankCreateView.as_view(), name="bank-create"),
    path("banks/add/amount/<int:pk>/", views.BankAddAmountView.as_view(), name="bank-add-amount"),
    path("banks/edit/<int:pk>/", views.BankUpdateView.as_view(), name="bank-update"),
    path("banks/delete/<int:pk>/", views.BankDeleteView.as_view(), name="bank-delete"),
    path("banks/transaction/delete/<int:pk>/<int:bank_pk>", views.BankTransactionDeleteView.as_view(),
         name="bank-transaction-delete"),

    path("banks/transfer/", views.BankTransferListView.as_view(), name="bank-transfer"),
    path("banks/transfer/create/", views.BankTransferView.as_view(), name="bank-transfer-create"),
    path("banks/transfer/delete/<int:pk>/", views.BankTransferDeleteView.as_view(), name="bank-transfer-delete"),

    path("capital/", views.CapitalView.as_view(), name="capital"),
    path("capital/<int:pk>/", views.CapitalDetailView.as_view(), name="capital-details"),
    path("capital/amount/add/", views.CapitalCreateView.as_view(), name="capital-add-amount"),
    path("capital/edit/<int:pk>/", views.CapitalUpdateView.as_view(), name="capital-update"),
    path("capital/delete/<int:pk>/", views.CapitalDeleteView.as_view(), name="capital-delete"),
    path("capital/history/<int:pk>/", views.CapitalHistoryView.as_view(), name="capital-history"),

    path("loan/", views.LoanView.as_view(), name="loan"),
    path("loan/<int:pk>/", views.LoanDetailView.as_view(), name="loan-details"),
    path("loan/amount/add/", views.LoanCreateView.as_view(), name="loan-add-amount"),
    path("loan/edit/<int:pk>/", views.LoanUpdateView.as_view(), name="loan-update"),
    path("loan/delete/<int:pk>/", views.LoanDeleteView.as_view(), name="loan-delete"),
    path("loan/history/<int:pk>/", views.LoanHistoryView.as_view(), name="loan-history"),
    path("loan/pay/<int:history_pk>/<int:bank_pk>/", views.LoanPayView.as_view(), name="loan-pay"),

    path("fixed-assets/", views.FixedAssetsView.as_view(), name="fixed-assets"),
    path("fixed-assets/<int:pk>/", views.FixedAssetsDetailView.as_view(), name="fixed-assets-details"),
    path("fixed-assets/create/", views.FixedAssetsCreateView.as_view(), name="fixed-assets-create"),
    path("fixed-assets/update/<int:pk>/", views.FixedAssetsUpdateView.as_view(), name="fixed-assets-update"),
    path("fixed-assets/delete/<int:pk>/", views.FixedAssetsDeleteView.as_view(), name="fixed-assets-delete"),
    path("fixed-assets/history/<int:pk>/", views.FixedAssetsHistoryView.as_view(), name="fixed-assets-history"),

    path("balance-sheet/", views.BalanceSheetView.as_view(), name="balance-sheet"),

    path("trial-balance/", views.TrialBalanceView.as_view(), name="trial-balance"),
    path("api/trial-balance/profit-loss/", views.ProfitLossApi.as_view(), name="api-profit-loss"),

    path("receipt/", views.ReceiptView.as_view(), name="receipt"),
    path("receipt/create/", views.ReceiptCreateView.as_view(), name="receipt-create"),
    path("payment/", views.PaymentView.as_view(), name="payment"),
    path("payment/create/", views.PaymentCreateView.as_view(), name="payment-create"),

    path("journal/", views.JournalListView.as_view(), name="journal"),
    path("journal/add/", views.JournalCreateView.as_view(), name="journal-create"),
    path("journal/edit/<int:pk>/", views.JournalUpdateView.as_view(), name="journal-update"),
    path("journal/delete/<int:pk>/", views.JournalDeleteView.as_view(), name="journal-delete"),

    path("depreciation/", views.AddDepreciationView.as_view(), name="depreciation"),

    path('company/', include("finsys.company.urls")),

]

users/urls.py
from django.urls import path, include
from .validator_api import UserNameValidator, EmailValidator

urlpatterns = [
    path("", include("users.general.urls")),
    path("password/forgot/", include("users.password_reset.urls")),
    path("password/change/", include("users.password_change.urls")),
    path("change/role/", include("users.role_change.urls")),
    path("verification/email/", include("users.email_verification.urls")),
    path("social/google/", include("users.django_google_auth.urls")),
    path("password/set/", include("users.set_password.urls")),
    path("resolve/account/lock/", include("users.resolve_lock.urls")),
    path("2FA/", include("users.second_factor_auth.urls")),
    path("deletion/", include("users.user_deletion.urls")),

    # validators
    path("validate/username/<str:username>/", UserNameValidator.as_view()),
    path("validate/email/<str:email>/", EmailValidator.as_view())
]

finsys/company/views.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

from finsys.company import forms
from finsys.models import CapitalModel, LoanModel, FixedAssetsModel
from users import models
from users.models import YearModel


class CompanyNotFound(generic.TemplateView):
    template_name = "finsys/company/company_404.html"


class CompanyCreateView(SuccessMessageMixin, generic.CreateView):
    model = models.CompanyModel
    form_class = forms.CompanyCreateForm
    template_name = "finsys/company/create.html"
    success_message = "Company created successfully"
    success_url = reverse_lazy("finsys:home")

    def form_valid(self, form):
        self.object = form.save()
        models.UserCompanyModel.objects.create(
            user=get_user_model().objects.get(pk=self.request.user.pk),
            company=self.object,
            role=models.UserCompanyModel.ADMIN
        )

        year_object, _ = models.YearModel.objects.get_or_create(company_id=self.object.pk, year=datetime.date.today().year)

        CapitalModel.objects.create(company=self.object, year_id=year_object.pk)
        LoanModel.objects.create(company=self.object, year_id=year_object.pk)
        FixedAssetsModel.objects.create(company=self.object, year_id=year_object.pk)
        return super(CompanyCreateView, self).form_valid(form)


class SwitchCompanyView(generic.RedirectView):
    pattern_name = "finsys:home"

    def get(self, request, *args, **kwargs):
        company = models.CompanyModel.objects.get(name=self.request.GET.get("c_name"))
        self.request.session["CURRENT_COMPANY_ID"] = company.id
        self.request.session["CURRENT_COMPANY_NAME"] = company.name
        return super(SwitchCompanyView, self).get(request, *args, **kwargs)


class CompanyDetailView(generic.DetailView):
    model = models.CompanyModel
    context_object_name = "company"
    template_name = "finsys/company/details.html"
    slug_field = "name"
    slug_url_kwarg = "name"

    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data(**kwargs)
        context["members"] = models.UserCompanyModel.objects.filter(
            company_id=self.request.session["CURRENT_COMPANY_ID"])
        return context


class CompanyUpdateView(SuccessMessageMixin, generic.UpdateView):
    model = models.CompanyModel
    form_class = forms.CompanyCreateForm
    template_name = "finsys/company/update.html"
    success_message = "Company updated successfully"

    def get_success_url(self):
        return reverse_lazy("finsys:company-detail", kwargs={"pk": self.object.company.id})


class CompanyDeleteView(generic.DeleteView):
    model = models.CompanyModel
    success_url = reverse_lazy("finsys:home")

    def get(self, request, *args, **kwargs):
        return super(CompanyDeleteView, self).delete(request, *args, **kwargs)


class MemberCreateView(generic.CreateView):
    model = models.UserCompanyModel
    form_class = forms.MemberCreateForm
    template_name = "finsys/company/member-add.html"

    def get_success_url(self):
        return reverse_lazy("finsys:company-detail", kwargs={"name": self.object.company.name})

    def form_valid(self, form):
        form.instance.company = models.CompanyModel.objects.get(pk=self.kwargs["pk"])
        return super(MemberCreateView, self).form_valid(form)


class MemberRoleChangeView(SuccessMessageMixin, generic.UpdateView):
    model = models.UserCompanyModel
    form_class = forms.MemberRoleChangeForm
    template_name = "finsys/company/change-role.html"
    success_message = "Member role changed successfully"

    def get_success_url(self):
        return reverse_lazy("finsys:company-detail", kwargs={"name": self.object.company.name})


class MemberRemoveView(SuccessMessageMixin, generic.DeleteView):
    model = models.UserCompanyModel
    success_message = "Member role removed successfully"

    def get_success_url(self):
        return reverse_lazy("finsys:company-detail", kwargs={"name": self.object.company.name})

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class YearSwitchView(generic.RedirectView):
    pattern_name = "finsys:home"

    def get(self, request, *args, **kwargs):
        year_object = YearModel.objects.get(year=self.request.GET.get("year"))
        self.request.session["CURRENT_YEAR_ID"] = year_object.id
        return super(YearSwitchView, self).get(request, *args, **kwargs)

finsys/views/account_views.py
from django.urls import reverse_lazy
from django.views import generic

from finsys.forms import AccountForm, AccountHistoryForm
from finsys.models import AccountModel, AccountHistoryModel, BankTransactionModel
from finsys.views.delete import DeleteView
from users.models import CompanyModel

class AccountListView(generic.ListView):
    context_object_name = 'accounts'
    ordering = ['name']
    template_name = "finsys/ledger.html"

    def get_queryset(self):
        return AccountModel.objects.filter(company_id=self.request.session["CURRENT_COMPANY_ID"])


class AccountDetailView(generic.DetailView):
    context_object_name = 'account'
    template_name = "finsys/ledger-details.html"

    def get_queryset(self):
        return AccountModel.objects.filter(company_id=self.request.session["CURRENT_COMPANY_ID"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["entries"] = AccountHistoryModel.objects.filter(account=self.object, is_deleted=False)
        return context


class AccountCreateView(generic.CreateView):
    form_class = AccountForm
    model = AccountModel
    template_name = "finsys/add-ledger.html"
    success_url = reverse_lazy("finsys:ledger")

    def get_initial(self):
        return {
            "company": self.request.session["CURRENT_COMPANY_ID"],
        }


class AccountUpdateView(generic.UpdateView):
    form_class = AccountForm
    model = AccountModel
    template_name = "finsys/add-ledger.html"
    success_url = reverse_lazy("finsys:account-list")


class AccountDeleteView(generic.DeleteView):
    model = AccountModel
    success_url = reverse_lazy("finsys:ledger")

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class AccountHistoryCreateView(generic.CreateView):
    model = AccountHistoryModel
    form_class = AccountHistoryForm
    template_name = "finsys/account-transaction.html"

    def form_valid(self, form):
        account = AccountModel.objects.get(pk=self.kwargs['pk'])
        company = CompanyModel.objects.get(pk=self.request.session["CURRENT_COMPANY_ID"])
        form.instance.user = self.request.user
        form.instance.account = account
        form.instance.from_where = account.name
        form.instance.company = company
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("finsys:ledger-details", kwargs={"pk": self.kwargs['pk']})


class AccountHistoryUpdateView(generic.UpdateView):
    model = AccountHistoryModel
    form_class = AccountHistoryForm
    template_name = "finsys/account-transaction.html"

    def get_success_url(self):
        return reverse_lazy("finsys:ledger-details", kwargs={"pk": self.kwargs['pk']})


class AccountHistoryDeleteView(DeleteView):
    model = AccountHistoryModel

    def get_success_url(self):
        return reverse_lazy("finsys:ledger-details", kwargs={"pk": self.kwargs['pk']})

    def get(self, request, *args, **kwargs):
        account = AccountModel.objects.filter(pk=kwargs['acc_pk']).first()
        entry = AccountHistoryModel.objects.filter(pk=kwargs['pk']).first()
        account.balance -= entry.amount
        account.save()
        BankTransactionModel.objects.filter(foreign_id=entry.id, head=account.name).update(is_deleted=True)

        return super().get(request, *args, **kwargs)


class AccountHistoryView(generic.ListView):
    template_name = "finsys/history.html"
    context_object_name = 'entries'
    ordering = ['-date']

    def get_queryset(self):
        instance = AccountHistoryModel.objects.get(pk=self.kwargs['pk'])
        if instance:
            return instance.history.all()
        return AccountHistoryModel.objects.none()

finsys/views/delete.py
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponseRedirect
from django.views.generic import View


class DeleteView(View):
    model = None
    success_url = None

    def get_model(self):
        if self.model:
            return self.model
        raise ImproperlyConfigured('You must define a model attribute')

    def get_success_url(self):
        if self.success_url:
            return self.success_url
        raise ImproperlyConfigured('You must define a success_url attribute')

    def delete(self, request, *args, **kwargs):
        if 'pk' not in kwargs:
            raise ImproperlyConfigured('You must specify a primary key - pk')

        model = self.get_model()
        queryset = model.objects.filter(pk=kwargs['pk']).first()
        queryset.is_deleted = True
        queryset.save()
        return HttpResponseRedirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        model = self.get_model()
        if not hasattr(model, 'is_deleted'):
            raise ImproperlyConfigured('model has no attribute \'is_deleted\'')
        return self.delete(request, *args, **kwargs)

finsys/views/depriciation_views.py
from django.urls import reverse_lazy
from django.views import generic

from finsys.models import DepreciationModel, FixedAssetsHistoryModel
from finsys.forms import DepreciationForm
from finsys.views.delete import DeleteView


class AddDepreciationView(generic.CreateView):
    model = DepreciationModel
    form_class = DepreciationForm
    template_name = "finsys/add-depreciation.html"
    success_url = reverse_lazy("finsys:journal")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

finsys/views/home_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from users.second_factor_auth.mixins import MultiFactorVerificationRequiredMixin

class HomeView(LoginRequiredMixin, MultiFactorVerificationRequiredMixin, TemplateView):
    template_name = "finsys/index.html"

finsys/templates/finsys/company/change-role.html
{% extends 'finsys/includes/base.html' %}
{% block title %}
    Change Role
{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mt-5">
        <div class="form-container">
            {% include 'finsys/includes/form.html' with form=form main_title='Change Role' %}
        </div>
    </div>

    <style>
        /* Glassmorphism Form */
        .form-container {
            display: flex;
            justify-content: center;
        }

        .form-box {
            width: 100%;
            max-width: 450px;
            background: rgba(255, 255, 255, 0.2);
            padding: 35px;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
            backdrop-filter: blur(10px);
            transition: all 0.3s ease-in-out;
            text-align: center;
        }

        .form-box:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2);
        }

        /* Floating Input Fields */
        .input-group {
            position: relative;
            margin-bottom: 20px;
        }

        .floating-input {
            width: 100%;
            padding: 12px;
            font-size: 16px;
            border: 2px solid transparent;
            border-bottom: 2px solid #ced4da;
            border-radius: 8px;
            background: rgba(255, 255, 255, 0.2);
            transition: all 0.3s ease-in-out;
        }

        .floating-label {
            position: absolute;
            left: 12px;
            top: 12px;
            font-size: 16px;
            color: #aaa;
            transition: all 0.3s ease-in-out;
            pointer-events: none;
        }

        .floating-input:focus,
        .floating-input:not(:placeholder-shown) {
            border-bottom: 2px solid #007bff;
        }

        .floating-input:focus + .floating-label,
        .floating-input:not(:placeholder-shown) + .floating-label {
            top: -10px;
            left: 10px;
            font-size: 14px;
            color: #007bff;
        }

        /* Animated Button */
        .add-btn {
            padding: 12px;
            font-size: 18px;
            font-weight: bold;
            color: #fff;
            background: linear-gradient(135deg, #007bff, #0056b3);
            border: none;
            border-radius: 8px;
            transition: all 0.3s ease-in-out;
            cursor: pointer;
        }

        .add-btn:hover {
            background: linear-gradient(135deg, #0056b3, #003f7f);
            transform: scale(1.05);
            box-shadow: 0 6px 20px rgba(0, 123, 255, 0.4);
        }

        /* Mobile Optimization */
        @media (max-width: 576px) {
            .form-box {
                width: 90%;
                padding: 25px;
            }
        }
    </style>

{% endblock %}

finsys/templates/finsys/company/company_404.html
{% extends 'finsys/includes/base.html' %}

{% block title %}
    Company Not Found
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-warning text-center shadow-sm p-4 rounded">
                    <h2 class="mb-3">You're Not Associated with Any Company</h2>
                    <p class="mb-4">You are not associated with any company. Please create a new company or request to
                        be added to an existing one.</p>
                    <div class="d-flex justify-content-center gap-3">
                        <a href="{% url 'finsys:company-create' %}" class="btn btn-primary">Create Company</a>
                        <a href="" class="btn btn-outline-secondary">Request Access</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

finsys/templates/finsys/company/create.html
{% extends 'finsys/includes/base.html' %}
{% block title %}
    ADD COMPANY
{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mt-5">
        <div class="form-container">
            {% include 'finsys/includes/form.html' with form=form main_title='Create Company' %}
        </div>
    </div>

    <style>
        /* Glassmorphism Form */
        .form-container {
            display: flex;
            justify-content: center;
        }

        .form-box {
            width: 100%;
            max-width: 450px;
            background: rgba(255, 255, 255, 0.2);
            padding: 35px;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
            backdrop-filter: blur(10px);
            transition: all 0.3s ease-in-out;
            text-align: center;
        }

        .form-box:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2);
        }

        /* Floating Input Fields */
        .input-group {
            position: relative;
            margin-bottom: 20px;
        }

        .floating-input {
            width: 100%;
            padding: 12px;
            font-size: 16px;
            border: 2px solid transparent;
            border-bottom: 2px solid #ced4da;
            border-radius: 8px;
            background: rgba(255, 255, 255, 0.2);
            transition: all 0.3s ease-in-out;
        }

        .floating-label {
            position: absolute;
            left: 12px;
            top: 12px;
            font-size: 16px;
            color: #aaa;
            transition: all 0.3s ease-in-out;
            pointer-events: none;
        }

        .floating-input:focus,
        .floating-input:not(:placeholder-shown) {
            border-bottom: 2px solid #007bff;
        }

        .floating-input:focus + .floating-label,
        .floating-input:not(:placeholder-shown) + .floating-label {
            top: -10px;
            left: 10px;
            font-size: 14px;
            color: #007bff;
        }

        /* Animated Button */
        .add-btn {
            padding: 12px;
            font-size: 18px;
            font-weight: bold;
            color: #fff;
            background: linear-gradient(135deg, #007bff, #0056b3);
            border: none;
            border-radius: 8px;
            transition: all 0.3s ease-in-out;
            cursor: pointer;
        }

        .add-btn:hover {
            background: linear-gradient(135deg, #0056b3, #003f7f);
            transform: scale(1.05);
            box-shadow: 0 6px 20px rgba(0, 123, 255, 0.4);
        }

        /* Mobile Optimization */
        @media (max-width: 576px) {
            .form-box {
                width: 90%;
                padding: 25px;
            }
        }
    </style>

{% endblock %}

finsys/templates/finsys/company/details.html
{% extends "finsys/includes/base.html" %}

{% block title %}
    {{ bank.name }}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="text-primary text-center text-lg-start">{{ company.name }}</h1>

        {% if NOT_VIEWER %}
            <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center mb-3">
                <div class="btn-group mt-3 mt-lg-0">
                    <a href="{% url 'finsys:company-member-add' company.id %}" class="btn btn-warning">Add Member</a>
                    <a href="{% url 'finsys:company-update' company.id %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'finsys:company-delete' company.pk %}" class="btn btn-warning">Delete</a>
                </div>
            </div>
        {% endif %}

        <div class="container mt-4">
            <h2 class="mb-3">Users</h2>

            {% include 'finsys/includes/date_filter.html' %}

            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable">
                    <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Role</th>
                        {% if NOT_VIEWER %}
                            <th>Change Role</th>
                            <th>Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody id="table-body">
                    {% for member in members %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ member.user.username }}</td>
                            <td>{{ member.role }}</td>
                            {% if NOT_VIEWER %}
                                <td><a href="{% url 'finsys:company-role-change' member.pk %}"
                                       class="btn btn-warning">Change</a></td>
                                <td><a href="{% url 'finsys:company-member-remove' member.id %}"
                                       class="btn btn-danger">Remove</a></td>
                            {% endif %}
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">No Entries Found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <style>
        @media (max-width: 768px) {
            .btn-group {
                width: 100%;
                display: flex;
                flex-direction: column;
            }

            .btn-group a {
                margin-bottom: 8px;
            }
        }
    </style>

{% endblock %}

finsys/templates/finsys/company/member-add.html
{% extends 'finsys/includes/base.html' %}
{% block title %}
    Add Member
{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mt-5">
        <div class="form-container">
            {% include 'finsys/includes/form.html' with form=form main_title='Add Member' %}
        </div>
    </div>

    <style>
        /* Glassmorphism Form */
        .form-container {
            display: flex;
            justify-content: center;
        }

        .form-box {
            width: 100%;
            max-width: 450px;
            background: rgba(255, 255, 255, 0.2);
            padding: 35px;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
            backdrop-filter: blur(10px);
            transition: all 0.3s ease-in-out;
            text-align: center;
        }

        .form-box:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2);
        }

        /* Floating Input Fields */
        .input-group {
            position: relative;
            margin-bottom: 20px;
        }

        .floating-input {
            width: 100%;
            padding: 12px;
            font-size: 16px;
            border: 2px solid transparent;
            border-bottom: 2px solid #ced4da;
            border-radius: 8px;
            background: rgba(255, 255, 255, 0.2);
            transition: all 0.3s ease-in-out;
        }

        .floating-label {
            position: absolute;
            left: 12px;
            top: 12px;
            font-size: 16px;
            color: #aaa;
            transition: all 0.3s ease-in-out;
            pointer-events: none;
        }

        .floating-input:focus,
        .floating-input:not(:placeholder-shown) {
            border-bottom: 2px solid #007bff;
        }

        .floating-input:focus + .floating-label,
        .floating-input:not(:placeholder-shown) + .floating-label {
            top: -10px;
            left: 10px;
            font-size: 14px;
            color: #007bff;
        }

        /* Animated Button */
        .add-btn {
            padding: 12px;
            font-size: 18px;
            font-weight: bold;
            color: #fff;
            background: linear-gradient(135deg, #007bff, #0056b3);
            border: none;
            border-radius: 8px;
            transition: all 0.3s ease-in-out;
            cursor: pointer;
        }

        .add-btn:hover {
            background: linear-gradient(135deg, #0056b3, #003f7f);
            transform: scale(1.05);
            box-shadow: 0 6px 20px rgba(0, 123, 255, 0.4);
        }

        /* Mobile Optimization */
        @media (max-width: 576px) {
            .form-box {
                width: 90%;
                padding: 25px;
            }
        }
    </style>

{% endblock %}