dawnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('finsys.urls', 'finsys'), namespace='finsys')),
    path('authentication/', include(('users.urls', 'users'), namespace='users')),
]

users/general/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # redirect user based on authentication and authorisation
    path('', views.RedirectUserView.as_view(), name="redirect-user"),
    # profile page
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),

    # user login
    path('login/', views.LoginView.as_view(), name='login'),
    # user logout
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # user registration
    path('register/', views.RegisterView.as_view(), name='signup'),

    # user update
    # change username
    path('username/<username>', views.ChangeUsername.as_view(), name='change-username'),
    # change fullname
    path('fullname/<username>', views.ChangeFullname.as_view(), name='change-fullname'),
    # change email
    path('email/<username>', views.ChangeEmail.as_view(), name='change-email'),

]

users/password_change/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # password change
    # two methods
    #
    # path -
    # using otp to verify and redirect to change password
    # path -

    # redirect the user to confirm and direct to the chosen method(otp/link)
    path('', views.RedirectUserView.as_view(), name='change-password-redirect'),

    # method - link
    # send a mail with an url to change the password
    path('send-mail/link/<token>/', views.ChangeSendLinkMail.as_view(), name='change-send-link-mail'),
    # redirect user to a message page
    path('send-mail/done/<token>/', views.MailSendDoneView.as_view(), name='change-mail-send-done'),

    # method - otp
    # send a mail with an otp
    path('send-mail/otp/<token>/', views.ChangeSendOTPMail.as_view(), name='change-send-otp-mail'),
    # resend otp
    path('resend-mail/', views.ChangeResendOTPMail.as_view(), name='change-resend-otp-mail'),
    # verify otp
    path('verify-otp/<token>/', views.ChangeVerifyOTPView.as_view(), name='change-verify-otp'),

    # common
    # change the password and redirect the user
    path('<uidb64>/<token>/', views.PasswordChangeView.as_view(), name='change-password'),
]

users/password_reset/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # forgot password
    # two methods
    # using an url to reset password
    # path -
    # using otp to verify and redirect to reset password

    path('', views.GetEmailView.as_view(), name='password-reset'),
    # redirect user to give their registered email and redirect to chosen path (otp/link)
    path('redirect/<token>/', views.RedirectUserView.as_view(), name='reset-password-redirect'),

    # forgot password link method
    # send an email with password reset link
    path('send-mail/link/<token>/', views.ResetSendLinkMail.as_view(), name='reset-send-link-mail'),
    # redirect user to a message page
    path('send-mail/done/<token>/', views.MailSendDoneView.as_view(), name='reset-mail-send-done'),

    # forgot password otp method
    # send an email with an otp number
    path('send-mail/otp/<token>/', views.ResetSendOTPMail.as_view(), name='reset-send-otp-mail'),
    # resend otp
    path('resend-mail/otp/', views.ResetResendOTPMail.as_view(), name='reset-resend-otp-mail'),
    # verify otp
    path('verify-otp/<token>/', views.ResetVerifyOTP.as_view(), name='reset-otp-verify'),

    # common for both method
    # reset the password
    path('<uidb64>/<token>/', views.PasswordResetView.as_view(), name='reset-password'),
    # redirect the user
    path('done/', views.PasswordResetDoneView.as_view(), name='reset-password-done'),
]

users/role_change/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # change the role and group of a user
    # an email will pass to the admins' email to verify and change role (user)
    path('send/mail/request/<role>/', views.RoleChangeRequestMail.as_view(), name='role-send-mail'),
    # show success message
    path('send/mail/done/', views.RoleChangeRequestSendDone.as_view(), name='role-send-mail-done'),

    # confirm the role change (admin)
    path("confirm/<username>/<role>/", views.RoleChangeConfirm.as_view(), name="role-change-confirm"),

    # change role and group (admin)
    path('accept/role/<uidb64>/<token>/', views.RoleChangeView.as_view(), name='role-change-accept'),
    # success mail
    path('accepted/mail/', views.RoleChangeDoneMail.as_view(), name='role-change-accept-mail'),
    # show messages
    path('done/', views.RoleChangeDone.as_view(), name='role-change-done'),

    # role change declined by admin sending mail to user
    path('declined/mail/', views.RoleChangeFailMail.as_view(), name='role-change-decline-mail'),
    # show messages
    path('fail/', views.RoleChangeDeclined.as_view(), name='role-change-fail'),
]

users/set_password/urls.py
from django.urls import path

from .views import SetPasswordView

urlpatterns = [
    path('', SetPasswordView.as_view(), name='set-password'),
]

users/urls.py
from django.urls import path, include
from .validator_api import UserNameValidator, EmailValidator

urlpatterns = [
    path("", include("users.general.urls")),
    path("password/forgot/", include("users.password_reset.urls")),
    path("password/change/", include("users.password_change.urls")),
    path("change/role/", include("users.role_change.urls")),
    path("verification/email/", include("users.email_verification.urls")),
    path("social/google/", include("users.django_google_auth.urls")),
    path("password/set/", include("users.set_password.urls")),
    path("resolve/account/lock/", include("users.resolve_lock.urls")),
    path("2FA/", include("users.second_factor_auth.urls")),
    path("deletion/", include("users.user_deletion.urls")),

    # validators
    path("validate/username/<str:username>/", UserNameValidator.as_view()),
    path("validate/email/<str:email>/", EmailValidator.as_view())
]

users/user_deletion/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # user deletion
    # send confirmation mail
    path('send-mail/', views.DeleteUserSendMail.as_view(), name='delete-send-mail'),
    # success message
    path('send-mail/done/', views.MailSendDoneView.as_view(), name='delete-mail-done'),

    # delete confirmation page
    path('confirm/<token>', views.DeleteUserConfirmation.as_view(), name='delete-user-confirm'),

    # delete declined
    path('decline/<token>', views.DeleteUseDecline.as_view(), name='delete-user-decline'),
    # delete confirmed
    path('accept/<token>/', views.DeleteUser.as_view(), name='delete-user'),
]

users/django_otp/forms.py
from django import forms


class OTPForm(forms.Form):
    """
    Form with field for otp
    """
    otp = forms.CharField(max_length=6, widget=forms.TextInput(attrs={"placeholder": "Enter OTP"}))

users/django_google_auth/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.http import HttpResponseServerError
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from django.core.exceptions import ImproperlyConfigured


def get_flow(state=None):
    return Flow.from_client_secrets_file(
        settings.GOOGLE_AUTH.get("client_secret_file"),
        scopes=settings.GOOGLE_AUTH.get("scopes"),
        redirect_uri=settings.GOOGLE_AUTH.get("redirect_uri"),
        state=state
    )


class GoogleLogin(View):

    def get(self, request):
        if not hasattr(settings, 'GOOGLE_AUTH'):
            raise ImproperlyConfigured("GOOGLE_AUTH is not configured")

        flow = get_flow()
        authorization_url, state = flow.authorization_url(
            access_type=settings.GOOGLE_AUTH.get("access_type"),
            prompt='select_account')
        request.session['GOOGLE_AUTH_STATE'] = state
        return redirect(authorization_url)


class GoogleCallback(View):

    def get_user_info(self):
        flow = get_flow(state=self.request.GET.get('GOOGLE_AUTH_STATE'))
        authorization_response = self.request.build_absolute_uri()
        flow.fetch_token(authorization_response=authorization_response)
        credentials = flow.credentials
        user_info_service = build('oauth2', 'v2', credentials=credentials)
        return user_info_service.userinfo().get().execute()

    def get(self, request, **kwargs):
        if request.GET.get('state') != request.session['GOOGLE_AUTH_STATE']:
            return HttpResponseServerError("Invalid google auth state")

        user_info = self.get_user_info()
        request.session['GOOGLE_AUTH_USER_INFO'] = user_info
        return redirect(reverse_lazy("users:google-redirect"))


class GoogleRedirect(View):
    model = get_user_model()
    template_name = 'general/login.html'
    group = None
    role = None
    redirect_url = None

    def user_exists(self, **kwargs):
        return self.model.objects.filter(**kwargs).exists()

    def get_user(self, **kwargs):
        return get_object_or_404(self.model, **kwargs)

    def get_redirect_url(self):
        if hasattr(settings, 'LOGIN_REDIRECT_URL'):
            return reverse_lazy(settings.LOGIN_REDIRECT_URL)

        if self.redirect_url:
            return reverse_lazy(self.redirect_url)

        raise ImproperlyConfigured("LOGIN_REDIRECT_URL is not configured")

    def login_user(self, user):
        login(self.request, user, backend="users.backends.UsernameAuthBackend")
        return redirect(self.get_redirect_url())

    def get_default_group(self):
        if hasattr(settings, "DEFAULT_USER_GROUP_NAME"):
            return get_object_or_404(Group, name=settings.DEFAULT_USER_GROUP_NAME)

        if self.group:
            return get_object_or_404(Group, name=self.group)

        raise ImproperlyConfigured("DEFAULT_USER_GROUP_NAME is not configured")

    def get_default_role(self):
        user_model = get_user_model()
        if hasattr(settings, "DEFAULT_USER_GROUP_NAME"):
            return getattr(user_model, settings.DEFAULT_USER_ROLE)

        if self.group:
            return getattr(user_model, self.role)

        raise ImproperlyConfigured("DEFAULT_USER_GROUP_NAME is not configured")

    def add_group(self, user):
        user.groups.add(self.get_default_group())
        user.save()
        return self.login_user(user)

    @staticmethod
    def get_names(name):
        names = name.split()
        print(name, name)
        if len(names) == 1:
            return names[0], ""
        elif len(names) == 2:
            return names[0], names[1]

    def register_user(self, user_info):
        first_name, last_name = self.get_names(user_info.get("name"))
        data = {
            "email": user_info.get("email"),
            "username": user_info.get("email"),
            "first_name": first_name,
            "last_name": last_name,
            "role": self.get_default_role(),
            "email_verified": True,
        }
        user = get_user_model().objects.create_user(**data)
        return self.add_group(user)

    def get(self, request, **kwargs):
        user_info = request.session.pop('GOOGLE_AUTH_USER_INFO')
        if self.user_exists(email=user_info.get('email')):
            user = self.get_user(email=user_info.get("email"))
            return self.login_user(user)
        else:
            return self.register_user(user_info)

users/django_mail/views.py
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import redirect
from django.views import generic, View

from users.mixins import FormMixin
from .forms import EmailForm
from .mixins import SendEmailMixin


class GetEmailView(FormMixin, generic.TemplateView):
    template_name = None
    form_class = EmailForm

    def form_valid(self, form):
        self.request.session['USER_EMAIL'] = form.cleaned_data['email']
        return redirect(self.get_success_url())


class SendEmailView(SendEmailMixin, View):
    """
    View to send email using django's smtp system
    """
    success_url = None

    def get_success_url(self):
        if self.success_url:
            return self.success_url
        raise ImproperlyConfigured(
            f"{self.__class__.__name__} missing 'success_url' attribute, define 'success_url' attribute or define "
            f"'get_success_url' method")

    def get(self, request, *args, **kwargs):
        self.send_mail()
        return redirect(self.get_success_url())

users/django_otp/views.py
import random

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import redirect
from django.views import generic, View

from users.mixins import FormMixin
from users.models import OTPModel
from users.utils import get_object_or_redirect
from .forms import OTPForm


def generate_otp():
    min_ = "1" + ("0" * (settings.OTP_LENGTH - 1))
    max_ = "9" * settings.OTP_LENGTH
    return random.randint(int(min_), int(max_))


class OTPCreateView(View):
    success_url = None
    user = None

    def get_user_model(self):
        return self.user

    def get_success_url(self):
        return self.success_url

    def get(self, request, *args, **kwargs):
        if not hasattr(settings, "OTP_LENGTH"):
            raise ImproperlyConfigured(f"{self.__class__.__name__} has no OTP_LENGTH specified")
        if not hasattr(settings, "OTP_EXPIRY"):
            raise ImproperlyConfigured(f"{self.__class__.__name__} has no OTP_EXPIRY specified")

        user = self.get_user_model()
        otp = OTPModel(user=user, otp=generate_otp())
        otp.save()
        request.session["OTP_ID"] = otp.id
        return redirect(self.get_success_url())


class VerifyOTPView(FormMixin, generic.TemplateView):
    """
    verify the OTP
    """
    template_name = None
    model = OTPModel
    success_url = None
    form_class = OTPForm
    user_kwargs = {}

    def get_user_kwargs(self):
        return self.user_kwargs

    def get_user_model(self):
        return get_object_or_redirect(get_user_model(), **self.get_user_kwargs())

    def get_otp_model(self, otp_number):
        return get_object_or_redirect(self.get_model(), otp=otp_number)

    def get_model(self):
        if self.model is None:
            raise ImproperlyConfigured(f"{self.__class__.__name__} has no model specified")
        return self.model

    def otp_invalid(self, form, otp_model):
        form.add_error("otp", "OTP is not valid")
        otp_model.delete()
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        if not self.get_model().objects.filter(user=self.get_user_model()):
            return self.otp_invalid(form)

        otp_number = form.cleaned_data.get("otp")
        otp_model = self.get_otp_model(otp_number)
        if otp_model.user.id != self.get_user_model().id:
            return self.otp_invalid(form, otp_model)

        if otp_number != otp_model.otp:
            return self.otp_invalid(form, otp_model)

        if otp_model.is_expired():
            return self.otp_invalid(form, otp_model)

        otp_model.delete()
        return redirect(self.get_success_url())

users/second_factor_auth/email_factor/views.py
from braces.views import LoginRequiredMixin
from django.conf import settings
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import RedirectView

from users.django_mail import views as mail_views
from users.django_otp import views as otp_views
from users.models import OTPModel
from users.token.user_token import token_generator, PathTokenValidationMixin


class ResendOTPView(RedirectView):

    def get_redirect_url(self):
        token = token_generator.generate_token(path="second-factor-verification").make_token(self.request.user)
        return reverse_lazy(settings.SECOND_FACTOR_VERIFICATION_URL, kwargs={"token": token})


class SendOTPView(LoginRequiredMixin, PathTokenValidationMixin, mail_views.SendEmailView):
    pre_path = "second-factor-verification"

    email_subject = "2FA Authentication"
    send_html_email = True
    email_template_name = "users/second_factor_auth/email_factor/otp.html"

    def get_to_email(self):
        return self.request.user.email

    def get_email_context_data(self):
        otp_model = OTPModel.objects.create(
            user=self.request.user,
            otp=otp_views.generate_otp(),
        )
        return {
            "otp": otp_model.otp,
            "user": self.request.user.username,
        }

    def get_success_url(self):
        token = token_generator.generate_token(path="email-factor-send").make_token(self.request.user)
        return reverse_lazy("users:email-factor-verify", kwargs={"token": token})


class VerifyOTP(LoginRequiredMixin, PathTokenValidationMixin, otp_views.VerifyOTPView):
    """
    verify the otp that is provided by the user
    """
    pre_path = "email-factor-send"
    template_name = "users/second_factor_auth/email_factor/verify-otp.html"

    def get_user_model(self):
        return self.request.user

    def verify_second_factor(self):
        self.request.user.verify_second_factor()
        self.request.user.verify_email()
        self.request.session["2FA_STATUS"] = True
        return reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def get_success_url(self):
        return self.verify_second_factor()

users/templates/users/general/login.html
{% extends 'users/common/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Login | {{ SITE_NAME }}{% endblock %}

{% block content %}
    <div class="bg-white shadow-md rounded-lg p-8 max-w-md mx-auto">
        <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Login to Your Account</h2>

        <form method="POST" class="space-y-5">
            {% csrf_token %}
            {% include 'users/common/form.html' with form=form %}

            <div class="flex justify-between items-center text-sm">
                <a href="{% url 'users:password-reset'  %}" class="text-blue-600 hover:underline">Forgot password?</a>
            </div>

            <button type="submit"
                    class="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition">
                Login
            </button>
        </form>

        <div class="mt-6">
            <div class="relative">
                <div class="absolute inset-0 flex items-center">
                    <div class="w-full border-t border-gray-300"></div>
                </div>
                <div class="relative flex justify-center text-sm text-gray-500 bg-white px-2">
                    Or continue with
                </div>
            </div>

            <a href="{% url 'users:google-login' %}"
               class="mt-4 flex items-center justify-center w-full border border-gray-300 rounded-md py-2 px-4 text-sm font-medium text-gray-700 hover:bg-gray-50 transition">
                <img src="{% static 'users/img/google-icon.svg' %}" alt="Google" class="h-5 w-5 mr-2">
                Google
            </a>
        </div>

        <p class="mt-6 text-center text-sm text-gray-600">
            Don't have an account?
            <a href="{% url 'users:signup' %}" class="text-blue-600 hover:underline">Sign up</a>
        </p>
    </div>
{% endblock %}

users/templates/users/general/profile.html
{% extends "users/common/base.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
    <div class="flex flex-col lg:flex-row bg-white rounded-lg shadow-lg overflow-hidden">

        <!-- Sidebar -->
        <aside class="w-full lg:w-1/4 bg-gray-100 border-r px-6 py-8 space-y-6 text-lg font-medium text-gray-700">
            <div class="text-xl font-bold text-blue-600 mb-4">Settings</div>
            <a href="#personal" class="block hover:text-blue-600">Personal Info</a>
            <a href="#security" class="block hover:text-blue-600">Security</a>
            <a href="#account" class="block hover:text-blue-600">Account Actions</a>
        </aside>

        <!-- Main Content -->
        <section class="flex-1 px-8 py-8 space-y-12">

            <!-- Personal Info -->
            <div id="personal" class="space-y-4">
                <h2 class="text-2xl font-semibold text-gray-800 border-b pb-2">Personal Info</h2>

                <div class="flex justify-between">
                    <span>Username:</span>
                    <a href="{% url 'users:change-username' username=user.username %}"
                       class="text-blue-600 underline">{{ user.username }}</a>
                </div>

                <div class="flex justify-between">
                    <span>Full Name:</span>
                    <a href="{% url 'users:change-fullname' username=user.username %}"
                       class="text-blue-600 underline">{{ user.first_name }} {{ user.last_name }}</a>
                </div>

                <div class="flex justify-between">
                    <span>Email:</span>
                    {% if user.email %}
                        <span>
            {{ user.email }}
                            {% if not user.email_verified %}
                                <a href="{% url 'users:verification-email-redirect' %}"
                                   class="text-red-600 ml-2 underline">Verify</a>
                            {% endif %}
          </span>
                    {% else %}
                        <a href="{% url 'users:change-email' username=user.username %}" class="text-blue-600 underline">Add
                            Email</a>
                    {% endif %}
                </div>
            </div>

            <!-- Security -->
            <div id="security" class="space-y-4">
                <h2 class="text-2xl font-semibold text-gray-800 border-b pb-2">Security</h2>

                {% if not user.has_usable_password %}
                    <p class="text-red-600 text-sm">
                        You haven’t set a password yet.
                        <a href="{% url 'users:set-password' %}" class="underline">Set password</a>
                    </p>
                {% endif %}

                <a href="{% url 'users:change-password-redirect' %}">
                    <button class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">Change Password</button>
                </a>
            </div>

            <!-- Account Actions -->
            <div id="account" class="space-y-4">
                <h2 class="text-2xl font-semibold text-gray-800 border-b pb-2">Account Actions</h2>

                <a href="{% url 'users:role-send-mail' role='STAFF' %}">
                    <button class="w-full bg-indigo-600 text-white py-2 rounded hover:bg-indigo-700">Request Role
                        Change
                    </button>
                </a>
                <a href="{% url 'users:delete-send-mail' %}">
                    <button class="w-full bg-red-600 text-white py-2 rounded hover:bg-red-700">Delete Account</button>
                </a>
                <a href="{% url 'users:logout' %}">
                    <button class="w-full bg-gray-300 text-gray-800 py-2 rounded hover:bg-gray-400">Logout</button>
                </a>
            </div>

        </section>
    </div>
{% endblock %}

users/templates/users/general/register.html
{% extends 'users/common/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Sign Up | {{ SITE_NAME }}{% endblock %}

{% block content %}
    <div class="bg-white shadow-md rounded-lg p-8 max-w-md mx-auto">
        <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Create an Account</h2>

        <form method="POST" class="space-y-5">
            {% csrf_token %}
            {% include 'users/common/form.html' with form=form %}

            <button type="submit"
                    class="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition">
                Sign Up
            </button>
        </form>

        <div class="mt-6">
            <div class="relative">
                <div class="absolute inset-0 flex items-center">
                    <div class="w-full border-t border-gray-300"></div>
                </div>
                <div class="relative flex justify-center text-sm text-gray-500 bg-white px-2">
                    Or continue with
                </div>
            </div>

            <a href="{% url 'users:google-login' %}"
               class="mt-4 flex items-center justify-center w-full border border-gray-300 rounded-md py-2 px-4 text-sm font-medium text-gray-700 hover:bg-gray-50 transition">
                <img src="{% static 'users/img/google-icon.svg' %}" alt="Google" class="h-5 w-5 mr-2">
                Google
            </a>
        </div>

        <p class="mt-6 text-center text-sm text-gray-600">
            Already have an account?
            <a href="{% url 'users:login' %}" class="text-blue-600 hover:underline">Log in</a>
        </p>
    </div>
{% endblock %}

{% block scripts %}
	<script src="{% static 'users/js/validators/usernameValidator.js' %}"></script>
	<script src="{% static 'users/js/validators/passwordValidator.js' %}"></script>
	<script src="{% static 'users/js/validators/emailValidator.js' %}"></script>
{% endblock %}

users/templates/users/general/update.html
{% extends "users/common/base.html" %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="flex items-center justify-center min-h-[85vh] px-4">
        <div class="bg-white shadow-md rounded-lg max-w-lg w-full p-8">
            <h2 class="text-xl font-semibold text-gray-800 text-center mb-6">{{ title }}</h2>

            <form method="post" class="space-y-4">
                {% csrf_token %}
                {% include "users/common/form.html" with form=form %}

                <button type="submit"
                        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition">
                    Update
                </button>
            </form>
        </div>
    </div>
{% endblock %}