dawnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('finsys.urls', 'finsys'), namespace='finsys')),
    path('authentication/', include(('users.urls', 'users'), namespace='users')),
]

users/general/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # redirect user based on authentication and authorisation
    path('', views.RedirectUserView.as_view(), name="redirect-user"),
    # profile page
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),

    # user login
    path('login/', views.LoginView.as_view(), name='login'),
    # user logout
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # user registration
    path('register/', views.RegisterView.as_view(), name='signup'),

    # user update
    # change username
    path('username/<username>', views.ChangeUsername.as_view(), name='change-username'),
    # change fullname
    path('fullname/<username>', views.ChangeFullname.as_view(), name='change-fullname'),
    # change email
    path('email/<username>', views.ChangeEmail.as_view(), name='change-email'),

]

users/password_reset/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # forgot password
    # two methods
    # using an url to reset password
    # path -
    # using otp to verify and redirect to reset password

    path('', views.GetEmailView.as_view(), name='password-reset'),
    # redirect user to give their registered email and redirect to chosen path (otp/link)
    path('redirect/<token>/', views.RedirectUserView.as_view(), name='reset-password-redirect'),

    # forgot password link method
    # send an email with password reset link
    path('send-mail/link/<token>/', views.ResetSendLinkMail.as_view(), name='reset-send-link-mail'),
    # redirect user to a message page
    path('send-mail/done/<token>/', views.MailSendDoneView.as_view(), name='reset-mail-send-done'),

    # forgot password otp method
    # send an email with an otp number
    path('send-mail/otp/<token>/', views.ResetSendOTPMail.as_view(), name='reset-send-otp-mail'),
    # resend otp
    path('resend-mail/otp/', views.ResetResendOTPMail.as_view(), name='reset-resend-otp-mail'),
    # verify otp
    path('verify-otp/<token>/', views.ResetVerifyOTP.as_view(), name='reset-otp-verify'),

    # common for both method
    # reset the password
    path('<uidb64>/<token>/', views.PasswordResetView.as_view(), name='reset-password'),
    # redirect the user
    path('done/', views.PasswordResetDoneView.as_view(), name='reset-password-done'),
]

users/role_change/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # change the role and group of a user
    # an email will pass to the admins' email to verify and change role (user)
    path('send/mail/request/<role>/', views.RoleChangeRequestMail.as_view(), name='role-send-mail'),
    # show success message
    path('send/mail/done/', views.RoleChangeRequestSendDone.as_view(), name='role-send-mail-done'),

    # confirm the role change (admin)
    path("confirm/<username>/<role>/", views.RoleChangeConfirm.as_view(), name="role-change-confirm"),

    # change role and group (admin)
    path('accept/role/<uidb64>/<token>/', views.RoleChangeView.as_view(), name='role-change-accept'),
    # success mail
    path('accepted/mail/', views.RoleChangeDoneMail.as_view(), name='role-change-accept-mail'),
    # show messages
    path('done/', views.RoleChangeDone.as_view(), name='role-change-done'),

    # role change declined by admin sending mail to user
    path('declined/mail/', views.RoleChangeFailMail.as_view(), name='role-change-decline-mail'),
    # show messages
    path('fail/', views.RoleChangeDeclined.as_view(), name='role-change-fail'),
]

users/urls.py
from django.urls import path, include
from .validator_api import UserNameValidator, EmailValidator

urlpatterns = [
    path("", include("users.general.urls")),
    path("password/forgot/", include("users.password_reset.urls")),
    path("password/change/", include("users.password_change.urls")),
    path("change/role/", include("users.role_change.urls")),
    path("verification/email/", include("users.email_verification.urls")),
    path("social/google/", include("users.django_google_auth.urls")),
    path("password/set/", include("users.set_password.urls")),
    path("resolve/account/lock/", include("users.resolve_lock.urls")),
    path("2FA/", include("users.second_factor_auth.urls")),
    path("deletion/", include("users.user_deletion.urls")),

    # validators
    path("validate/username/<str:username>/", UserNameValidator.as_view()),
    path("validate/email/<str:email>/", EmailValidator.as_view())
]

users/django_otp/forms.py
from django import forms


class OTPForm(forms.Form):
    """
    Form with field for otp
    """
    otp = forms.CharField(max_length=6, widget=forms.TextInput(attrs={"placeholder": "Enter OTP"}))

users/django_google_auth/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.http import HttpResponseServerError
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from django.core.exceptions import ImproperlyConfigured


def get_flow(state=None):
    return Flow.from_client_secrets_file(
        settings.GOOGLE_AUTH.get("client_secret_file"),
        scopes=settings.GOOGLE_AUTH.get("scopes"),
        redirect_uri=settings.GOOGLE_AUTH.get("redirect_uri"),
        state=state
    )


class GoogleLogin(View):

    def get(self, request):
        if not hasattr(settings, 'GOOGLE_AUTH'):
            raise ImproperlyConfigured("GOOGLE_AUTH is not configured")

        flow = get_flow()
        authorization_url, state = flow.authorization_url(
            access_type=settings.GOOGLE_AUTH.get("access_type"),
            prompt='select_account')
        request.session['GOOGLE_AUTH_STATE'] = state
        return redirect(authorization_url)


class GoogleCallback(View):

    def get_user_info(self):
        flow = get_flow(state=self.request.GET.get('GOOGLE_AUTH_STATE'))
        authorization_response = self.request.build_absolute_uri()
        flow.fetch_token(authorization_response=authorization_response)
        credentials = flow.credentials
        user_info_service = build('oauth2', 'v2', credentials=credentials)
        return user_info_service.userinfo().get().execute()

    def get(self, request, **kwargs):
        if request.GET.get('state') != request.session['GOOGLE_AUTH_STATE']:
            return HttpResponseServerError("Invalid google auth state")

        user_info = self.get_user_info()
        request.session['GOOGLE_AUTH_USER_INFO'] = user_info
        return redirect(reverse_lazy("users:google-redirect"))


class GoogleRedirect(View):
    model = get_user_model()
    template_name = 'general/login.html'
    group = None
    role = None
    redirect_url = None

    def user_exists(self, **kwargs):
        return self.model.objects.filter(**kwargs).exists()

    def get_user(self, **kwargs):
        return get_object_or_404(self.model, **kwargs)

    def get_redirect_url(self):
        if hasattr(settings, 'LOGIN_REDIRECT_URL'):
            return reverse_lazy(settings.LOGIN_REDIRECT_URL)

        if self.redirect_url:
            return reverse_lazy(self.redirect_url)

        raise ImproperlyConfigured("LOGIN_REDIRECT_URL is not configured")

    def login_user(self, user):
        login(self.request, user, backend="users.backends.UsernameAuthBackend")
        return redirect(self.get_redirect_url())

    def get_default_group(self):
        if hasattr(settings, "DEFAULT_USER_GROUP_NAME"):
            return get_object_or_404(Group, name=settings.DEFAULT_USER_GROUP_NAME)

        if self.group:
            return get_object_or_404(Group, name=self.group)

        raise ImproperlyConfigured("DEFAULT_USER_GROUP_NAME is not configured")

    def get_default_role(self):
        user_model = get_user_model()
        if hasattr(settings, "DEFAULT_USER_GROUP_NAME"):
            return getattr(user_model, settings.DEFAULT_USER_ROLE)

        if self.group:
            return getattr(user_model, self.role)

        raise ImproperlyConfigured("DEFAULT_USER_GROUP_NAME is not configured")

    def add_group(self, user):
        user.groups.add(self.get_default_group())
        user.save()
        return self.login_user(user)

    @staticmethod
    def get_names(name):
        names = name.split()
        print(name, name)
        if len(names) == 1:
            return names[0], ""
        elif len(names) == 2:
            return names[0], names[1]

    def register_user(self, user_info):
        first_name, last_name = self.get_names(user_info.get("name"))
        data = {
            "email": user_info.get("email"),
            "username": user_info.get("email"),
            "first_name": first_name,
            "last_name": last_name,
            "role": self.get_default_role(),
            "email_verified": True,
        }
        user = get_user_model().objects.create_user(**data)
        return self.add_group(user)

    def get(self, request, **kwargs):
        user_info = request.session.pop('GOOGLE_AUTH_USER_INFO')
        if self.user_exists(email=user_info.get('email')):
            user = self.get_user(email=user_info.get("email"))
            return self.login_user(user)
        else:
            return self.register_user(user_info)

users/django_mail/views.py
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import redirect
from django.views import generic, View

from users.mixins import FormMixin
from .forms import EmailForm
from .mixins import SendEmailMixin


class GetEmailView(FormMixin, generic.TemplateView):
    template_name = None
    form_class = EmailForm

    def form_valid(self, form):
        self.request.session['USER_EMAIL'] = form.cleaned_data['email']
        return redirect(self.get_success_url())


class SendEmailView(SendEmailMixin, View):
    """
    View to send email using django's smtp system
    """
    success_url = None

    def get_success_url(self):
        if self.success_url:
            return self.success_url
        raise ImproperlyConfigured(
            f"{self.__class__.__name__} missing 'success_url' attribute, define 'success_url' attribute or define "
            f"'get_success_url' method")

    def get(self, request, *args, **kwargs):
        self.send_mail()
        return redirect(self.get_success_url())

users/django_otp/views.py
import random

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import redirect
from django.views import generic, View

from users.mixins import FormMixin
from users.models import OTPModel
from users.utils import get_object_or_redirect
from .forms import OTPForm


def generate_otp():
    min_ = "1" + ("0" * (settings.OTP_LENGTH - 1))
    max_ = "9" * settings.OTP_LENGTH
    return random.randint(int(min_), int(max_))


class OTPCreateView(View):
    success_url = None
    user = None

    def get_user_model(self):
        return self.user

    def get_success_url(self):
        return self.success_url

    def get(self, request, *args, **kwargs):
        if not hasattr(settings, "OTP_LENGTH"):
            raise ImproperlyConfigured(f"{self.__class__.__name__} has no OTP_LENGTH specified")
        if not hasattr(settings, "OTP_EXPIRY"):
            raise ImproperlyConfigured(f"{self.__class__.__name__} has no OTP_EXPIRY specified")

        user = self.get_user_model()
        otp = OTPModel(user=user, otp=generate_otp())
        otp.save()
        request.session["OTP_ID"] = otp.id
        return redirect(self.get_success_url())


class VerifyOTPView(FormMixin, generic.TemplateView):
    """
    verify the OTP
    """
    template_name = None
    model = OTPModel
    success_url = None
    form_class = OTPForm
    user_kwargs = {}

    def get_user_kwargs(self):
        return self.user_kwargs

    def get_user_model(self):
        return get_object_or_redirect(get_user_model(), **self.get_user_kwargs())

    def get_otp_model(self, otp_number):
        return get_object_or_redirect(self.get_model(), otp=otp_number)

    def get_model(self):
        if self.model is None:
            raise ImproperlyConfigured(f"{self.__class__.__name__} has no model specified")
        return self.model

    def otp_invalid(self, form, otp_model):
        form.add_error("otp", "OTP is not valid")
        otp_model.delete()
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        if not self.get_model().objects.filter(user=self.get_user_model()):
            return self.otp_invalid(form)

        otp_number = form.cleaned_data.get("otp")
        otp_model = self.get_otp_model(otp_number)
        if otp_model.user.id != self.get_user_model().id:
            return self.otp_invalid(form, otp_model)

        if otp_number != otp_model.otp:
            return self.otp_invalid(form, otp_model)

        if otp_model.is_expired():
            return self.otp_invalid(form, otp_model)

        otp_model.delete()
        return redirect(self.get_success_url())

users/general/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from users.models import UserCompanyModel
from users.second_factor_auth.mixins import MultiFactorVerificationRequiredMixin
from . import forms, base_views


class RedirectUserView(base_views.RedirectUserView):
    """
    Users Redirect View, redirect logged-in user
    """

    def get_pattern_name(self):
        self.request.session["CURRENT_COMPANY_ID"] = UserCompanyModel.objects.filter(user=self.request.user).first().id
        return reverse_lazy("finsys:home")


class ProfileView(LoginRequiredMixin, MultiFactorVerificationRequiredMixin, generic.TemplateView):
    """
    user profile page
    """
    template_name = "users/general/profile.html"

    def get(self, request, *args, **kwargs):
        if kwargs.get("username") != request.user.username:
            return redirect(reverse_lazy("users:profile", kwargs={"username": request.user.username}))
        return super().get(request, kwargs.get("username"))


class LoginView(auth_views.LoginView):
    """
    Users Login View

    redirect user to url specified in settings.LOGIN_REDIRECT_URL
    set settings.LOGIN_REDIRECT_URL to 'users:redirect-logged-user'
    to redirect user based on the group or role
    """
    template_name = "users/general/login.html"
    form_class = forms.UserLoginForm
    redirect_authenticated_user = True
    pattern_name = "users:redirect-user"

    def get_redirect_url(self):
        return reverse_lazy(self.pattern_name)

    def form_valid(self, form):
        form.reset_login_attempts()
        self.request.session.cycle_key()
        return super().form_valid(form)

    def form_invalid(self, form):
        if "account_locked" in form.error_messages:
            return redirect("users:get-email-lock")
        return super().form_invalid(form)


class LogoutView(auth_views.LogoutView):
    """
    Users Logout View

    redirect user to login page
    """
    next_page = "users:login"
    http_method_names = ["get", "post", "put"]
    success_url = reverse_lazy("users:login")

    def get_success_url(self):
        return self.success_url

    def get(self, request, *args, **kwargs):
        request.user.un_verify_second_factor()
        return super().post(request, *args, **kwargs)


class RegisterView(base_views.BaseUserRegistrationView):
    """
    User creation/registration view

    regular user is created and redirected to add the user in to a group
    """
    template_name = "users/general/register.html"
    success_url = reverse_lazy("users:login")

    def get_success_url(self, *args, **kwargs):
        self.request.session["user_id"] = self.object.id
        return self.success_url


class ChangeUsername(base_views.UpdateUser):
    form_class = forms.ChangeUsernameForm
    title = "Username"


class ChangeFullname(base_views.UpdateUser):
    form_class = forms.ChangeFullnameForm
    title = "Fullname"


class ChangeEmail(base_views.UpdateUser):
    form_class = forms.ChangeEmailForm
    title = "Email"

    def change_email_status(self):
        self.object.update(email_verified=False)

    def get_success_url(self):
        self.change_email_status()
        return super().get_success_url()

users/set_password/views.py
from braces.views import LoginRequiredMixin
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views.generic import FormView

from .forms import PasswordSetForm


class SetPasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/set-password/set_password.html'
    form_class = PasswordSetForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        logout(self.request)
        return reverse_lazy('users:redirect-user')

users/templates/users/resolve-lock/get-mail.html
{% extends "users/common/base.html" %}
{% block title %}Account Locked{% endblock %}

{% block content %}
    <div class="flex items-center justify-center min-h-[85vh] px-4">
        <div class="bg-white shadow-md rounded-lg max-w-md w-full p-8">
            <h1 class="text-2xl font-bold text-red-600 text-center mb-2">Account Locked</h1>

            <p class="text-red-500 text-center font-medium mb-4">
                Your account has been temporarily locked due to too many failed login attempts.
            </p>

            <p class="text-gray-700 text-center mb-6">
                Please enter your registered email address below. We’ll send you a link to verify your identity and
                unlock your account.
            </p>

            <form method="post" novalidate class="space-y-4">
                {% csrf_token %}
                {% include "users/common/form.html" with form=form %}

                <button type="submit"
                        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition">
                    Send Unlock Link
                </button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/resolve-lock/otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your OTP Code</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333333;
            background-color: #f4f4f4;
            padding: 20px;
        }

        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .header {
            background: linear-gradient(135deg, #4CAF50 0%, #45a049 100%);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }

        .header h1 {
            font-size: 28px;
            font-weight: 600;
            margin-bottom: 10px;
        }

        .header p {
            font-size: 16px;
            opacity: 0.9;
        }

        .content {
            padding: 40px 30px;
        }

        .greeting {
            font-size: 18px;
            margin-bottom: 20px;
            color: #2c3e50;
        }

        .message {
            font-size: 16px;
            margin-bottom: 30px;
            color: #555555;
            line-height: 1.7;
        }

        .otp-container {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 12px;
            padding: 30px;
            text-align: center;
            margin: 30px 0;
            box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);
        }

        .otp-label {
            color: white;
            font-size: 14px;
            font-weight: 500;
            margin-bottom: 15px;
            text-transform: uppercase;
            letter-spacing: 1px;
            opacity: 0.9;
        }

        .otp-code {
            background-color: white;
            color: #333333;
            font-size: 36px;
            font-weight: 700;
            letter-spacing: 8px;
            padding: 20px;
            border-radius: 8px;
            display: inline-block;
            font-family: 'Courier New', monospace;
            box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);
            margin: 0 auto;
            min-width: 200px;
        }

        .copy-btn {
            background-color: rgba(255, 255, 255, 0.2);
            color: white;
            border: 2px solid rgba(255, 255, 255, 0.3);
            padding: 10px 20px;
            border-radius: 20px;
            font-size: 14px;
            font-weight: 500;
            margin-top: 15px;
            cursor: pointer;
            transition: all 0.3s ease;
            display: inline-block;
            text-decoration: none;
        }

        .copy-btn:hover {
            background-color: rgba(255, 255, 255, 0.3);
            border-color: rgba(255, 255, 255, 0.5);
        }

        .timer-info {
            background-color: #fff3cd;
            border: 1px solid #ffeaa7;
            border-radius: 8px;
            padding: 20px;
            margin: 25px 0;
            text-align: center;
        }

        .timer-info .timer-icon {
            font-size: 24px;
            margin-bottom: 10px;
            color: #856404;
        }

        .timer-info p {
            font-size: 16px;
            color: #856404;
            margin: 0;
            font-weight: 500;
        }

        .timer-info .timer-text {
            font-size: 14px;
            color: #6c5714;
            margin-top: 5px;
        }

        .security-notice {
            background-color: #f8d7da;
            border: 1px solid #f5c6cb;
            border-radius: 6px;
            padding: 15px;
            margin: 20px 0;
        }

        .security-notice p {
            font-size: 14px;
            color: #721c24;
            margin: 0;
        }

        .security-notice strong {
            color: #491217;
        }

        .help-section {
            background-color: #e7f3ff;
            border-left: 4px solid #0066cc;
            padding: 20px;
            margin: 25px 0;
        }

        .help-section h3 {
            color: #0066cc;
            font-size: 16px;
            margin-bottom: 10px;
        }

        .help-section p {
            font-size: 14px;
            color: #004c99;
            margin: 0;
        }

        .footer {
            background-color: #f8f9fa;
            padding: 30px;
            text-align: center;
            border-top: 1px solid #e9ecef;
        }

        .footer p {
            font-size: 14px;
            color: #6c757d;
            margin-bottom: 10px;
        }

        .footer .company-info {
            font-size: 12px;
            color: #adb5bd;
            margin-top: 20px;
        }

        @media only screen and (max-width: 600px) {
            .email-container {
                margin: 0;
                border-radius: 0;
            }

            .header, .content, .footer {
                padding: 20px;
            }

            .header h1 {
                font-size: 24px;
            }

            .otp-code {
                font-size: 28px;
                letter-spacing: 4px;
                padding: 15px;
                min-width: 150px;
            }

            .otp-container {
                padding: 20px;
            }
        }
    </style>
</head>
<body>
<div class="email-container">
    <div class="header">
        <h1>Account Locked</h1>
        <p>Verify your identity to unlock your account</p>
    </div>

    <div class="content">
        <div class="greeting">
            Hello {{ user }},
        </div>

        <div class="message">
            Your account has been temporarily locked due to multiple unsuccessful login attempts. To unlock your
            account, please verify your identity using the One-Time Password (OTP) provided below.
        </div>

        <div class="otp-container">
            <div class="otp-label">Your OTP Code</div>
            <div class="otp-code">{{ otp }}</div>
        </div>

        <div class="timer-info">
            <div class="timer-icon">⏰</div>
            <p>This code will expire in 10 minutes</p>
            <div class="timer-text">Please enter it promptly to continue unlocking your account</div>
        </div>

        <div class="security-notice">
            <p><strong>Important:</strong> Do not share this code with anyone. Our team will never ask for your OTP.</p>
        </div>

        <div class="help-section">
            <h3>Didn't attempt to log in?</h3>
            <p>If you did not try to access your account, we recommend changing your password immediately and contacting
                our support team for assistance.</p>
        </div>

        <div class="message">
            Enter the OTP on the verification screen to proceed. If you need help, our support team is available to
            assist you.
        </div>
    </div>

    <div class="footer">
        <p>Your security is our priority.</p>
        <p>Best regards,<br>The [Company Name] Team</p>

        <div class="company-info">
            <p>[Company Name] | [Company Address]</p>
            <p>© 2025 [Company Name]. All rights reserved.</p>
        </div>
    </div>
</div>
</body>
</html>

users/templates/users/resolve-lock/verify-otp.html
{% extends "users/common/base.html" %}
{% block title %}Verify OTP{% endblock %}

{% block content %}
    <div class="flex items-center justify-center min-h-[85vh] px-4">
        <div class="bg-white shadow-md rounded-lg max-w-md w-full p-8">
            <h1 class="text-2xl font-bold text-blue-700 text-center mb-2">Unlock Your Account</h1>

            <h2 class="text-lg font-semibold text-gray-800 text-center mb-4">Enter the One-Time Password (OTP)</h2>

            <p class="text-gray-700 text-center mb-2">
                Your account has been temporarily locked due to multiple failed login attempts.
            </p>
            <p class="text-gray-600 text-center mb-6">
                We've sent a verification code to your registered email. Enter it below to unlock your account.
            </p>

            <form method="post" novalidate class="space-y-4">
                {% csrf_token %}
                {% include "users/common/form.html" with form=form %}

                <button type="submit"
                        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition">
                    Verify
                </button>
            </form>

            <div class="mt-4 text-center text-sm text-gray-600">
                <p>
                    Didn't receive the code?
                    <a href="{% url 'users:reset-resend-otp-mail' %}" class="text-blue-600 hover:underline">
                        Resend OTP
                    </a>
                </p>
            </div>

            <div class="mt-4 text-center text-xs text-gray-500">
                <p><strong>Note:</strong> This OTP is valid for 10 minutes. Do not share it with anyone.</p>
            </div>
        </div>
    </div>
{% endblock %}